export type ShopProfStateType = {
    shopUid: string,
    insta: string,
    o_insta: number,
    fb: string,
    o_fb: number,
    youtube: string,
    o_youtube: number,
    qr: string,
    o_qr: number,
    img: string,
    pv: string,
    t_pv: string,
    o_pv: number,
    url: string,
    t_url: string,
    o_url: number,
    sikaku: string,
    o_sikaku: number,
    manabi: string,
    manabi_url: string,
    yago: string,
    star: number;
}