export type UserState = {
    user: [],
    name: string,
    uid: string,
    icon: string | undefined
    namae: string,
    sei: string,
    tokoro: string,
    area: string,
    chip: number,
    stage: string,
    sns: string,
    o_sns: number,
    qr: string,
    o_qr: number,
    copy: string,
    o_copy: number,
    img: string,
    o_img: number,
    rogo: string,
    o_rogo: number,
    timesail: number,
    o_timesail: number,
    tanka: number,
    o_tanka: number,
    befor_img: string,
    after_img: string,
    befor_come: string,
    after_come: string,
    o_befor_come: number,
    o_after_come: number,
    pv: string,
    o_pv: number,
    make: boolean,
    nail: boolean,
    este: boolean,
    sonota: string
}